function BC_function_generator(function_name)
% Generate a template for a MATLAB function with pre-set text

% Define pre-set text
template_str = sprintf(['function output=%s(inputs)\n'...
                               '%%%% The function %s:\n' ...
                               '%%            [Provide a general description of the function here]\n' ...
                               '%%   Inputs:\n'...
                               '%%            -input1[type]: description \n' ...
                               '%% \n'...
                               '%% \n'...
                               '%%   Outputs:\n' ...
                               '%%             -output1[type]: description \n' ...
                               '%% \n'...
                               '%% \n'...
                               '%%  First version BC %s \n' ...
                               '%%%% \n'], function_name,function_name, date);

% Check if the function name is provided
if nargin >= 2
    error('Please, only provide the name of the function');
end

% Open  new file with the template

matlab.desktop.editor.newDocument(template_str);
end
